### ISSUE TITLE
SVG not being rerendered when data prop changes

### ISSUE THREAD

**Issue by pfefferniels** [WolfgangDrescher/vue-verovio-canvas#1] opened 2023-07-04 23:25 UTC
It seems that when the `data` prop is being updated, the verovio display does not get rerendered automatically. Is this intended behaviour? If not, I suspect that changing the watcher in `useVerovio.js` as follows would fix it:

    watch(data, () => {
        rerender.value = true; // <--
        loadScoreFile();
    });

**Comment by WolfgangDrescher** [comment] 2023-07-15 08:31
Hi @pfefferniels! Thanks for adding this issue. I finally found some time to create a reproduction repository. Please take a look at https://stackblitz.com/edit/github-e5n7cv?file=app.vue. But I was not able to reproduce your problem. When I change the content of the `VerovioCnavas` `data` prop, the score changes.

Could you explain in more detail why the score does not update in your setup, or ideally create a reproduction repository?

**Comment by WolfgangDrescher** [comment] 2024-01-24 22:34
For some reason in the reproduction repository an older version of `vue-verovio-canvas` was used where the bug was not yet introduces. This is now fixed in 2430d38 (Version 1.4.1).

**Closed as completed by WolfgangDrescher** 2024-01-24 22:34 UTC

**Comment by pfefferniels** [comment] 2024-01-24 22:37
O that's great news – thanks for fixing! (And also my apologies for not having come back to this …)
